version: '3'

services:
  app:
    build: .
    entrypoint: 'docker-entrypoint.sh'
    command: ['rails', 's', '-p', '3000', '-b', '0.0.0.0']
    env_file: .env
    ports:
      - 3000:3000
    depends_on: 
      - db
      - memcached
    volumes:
      - .:/greens-app

  db:
    image: mysql:8.0
    restart: always
    env_file: .env-db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    volumes:
      - db:/var/lib/mysql

  memcached:
    image: bitnami/memcached

volumes:
  db: