version: '3'

services:
  app:
    build: .
    entrypoint: 'docker-entrypoint.sh'
    command: ['rails', 's', '-p', '3000', '-b', '0.0.0.0']
    env_file: .env
    ports:
      - 3000:3000
    depends_on: 
      - db
      - memcached
    volumes:
      - .:/greens-app

  db:
    image: mysql:5.7
    restart: always
    env_file: .env
    environment: 
      - MYSQL_ROOT_PASSWORD=my-secret-password
    volumes:
      - db:/var/lib/mysql

  memcached:
    image: bitnami/memcached

volumes:
  db: